# -*- coding: utf-8 -*-
"""Edge pixels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""

import matplotlib.pyplot as plt
import numpy as np
import torch
import matplotlib.colors as mcolors
from sklearn.metrics import confusion_matrix, cohen_kappa_score

# Ensure model_sampled is on the correct device and in evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_sampled.to(device)
model_sampled.eval()

# Load the best model weights
try:
    model_sampled.load_state_dict(torch.load('best_mfa_cla_hsi_classifier_sampled.pth'))
    print("Successfully loaded best sampled model weights.")
except FileNotFoundError:
    print("Error: Best sampled model weights file 'best_mfa_cla_hsi_classifier_sampled.pth' not found.")
    print("Please ensure the training cell for sampled data was run and the model was saved.")
    exit()

# Re-create full predictions/labels to ensure alignment with spatial indices if needed
# (Assuming all_preds_full_eval and all_labels_full_eval are already correctly generated
# from the previous "Evaluate Model Performance" step)

# Get dimensions from the original HSI data
img_height, img_width, _ = hsi_data.shape

# 1. Identify Edge/Boundary Pixels
is_edge_pixel_map = np.zeros((img_height, img_width), dtype=bool)
pixel_idx_map = np.full((img_height, img_width), -1, dtype=int) # Map (r, c) to index in all_labels_full_eval

current_idx_counter = 0
for r in range(img_height):
    for c in range(img_width):
        if gt_data[r, c] != 0: # Only consider non-background pixels
            pixel_idx_map[r, c] = current_idx_counter
            current_idx_counter += 1

            # Check 8 neighbors
            is_boundary = False
            for dr in [-1, 0, 1]:
                for dc in [-1, 0, 1]:
                    if dr == 0 and dc == 0:
                        continue # Skip self

                    nr, nc = r + dr, c + dc
                    # Check if neighbor is out of bounds or a different class (including background 0)
                    if not (0 <= nr < img_height and 0 <= nc < img_width) or \
                       gt_data[nr, nc] == 0 or \
                       gt_data[nr, nc] != gt_data[r, c]:
                        is_boundary = True
                        break # Found a boundary condition, no need to check other neighbors
                if is_boundary:
                    break
            is_edge_pixel_map[r, c] = is_boundary

print(f"Total non-background pixels: {np.sum(gt_data != 0)}")
print(f"Total edge pixels identified: {np.sum(is_edge_pixel_map)}")

# 2. Extract Data for Edge Pixels
edge_labels = []
edge_preds = []
for r in range(img_height):
    for c in range(img_width):
        if is_edge_pixel_map[r, c]:
            idx_in_all_data = pixel_idx_map[r, c]
            if idx_in_all_data != -1: # Should always be true if is_edge_pixel_map[r,c] is true
                edge_labels.append(all_labels_full_eval[idx_in_all_data])
                edge_preds.append(all_preds_full_eval[idx_in_all_data])

edge_labels = np.array(edge_labels)
edge_preds = np.array(edge_preds)

print(f"Number of edge samples for evaluation: {len(edge_labels)}")

# 3. Evaluate Accuracy on Edge Pixels
if len(edge_labels) > 0:
    oa_edge = np.sum(edge_preds == edge_labels) / len(edge_labels)
    kappa_edge = cohen_kappa_score(edge_labels, edge_preds)

    cm_edge = confusion_matrix(edge_labels, edge_preds, labels=np.arange(num_classes)) # Ensure all classes are covered
    per_class_accuracy_edge = []
    for i in range(num_classes):
        correct_predictions_class_i = cm_edge[i, i]
        total_samples_class_i = np.sum(cm_edge[i, :])
        if total_samples_class_i > 0:
            per_class_accuracy_edge.append(correct_predictions_class_i / total_samples_class_i)
        else:
            per_class_accuracy_edge.append(np.nan) # Use NaN if no samples for the class

    aa_edge = np.nanmean(per_class_accuracy_edge) # Use nanmean to ignore NaNs

    print(f"\n--- Performance on Edge/Boundary Pixels ---")
    print(f"Overall Accuracy (OA) on edge pixels: {oa_edge:.4f}")
    print(f"Kappa Coefficient on edge pixels: {kappa_edge:.4f}")
    print(f"Average Accuracy (AA) on edge pixels: {aa_edge:.4f}")
    print("\nPer-class Accuracies on edge pixels:")
    for i, acc in enumerate(per_class_accuracy_edge):
        if not np.isnan(acc):
            print(f"  Class {i}: {acc:.4f}")
        else:
            print(f"  Class {i}: N/A (no edge samples)")
else:
    print("\nNo edge pixels found for evaluation.")

# 4. Visualize Edge Pixels and Misclassifications
# Create a visualization map:
# 0: Background
# 1: Correctly classified edge pixel
# 2: Misclassified edge pixel
# 3: Correctly classified non-edge pixel
# 4: Misclassified non-edge pixel

vis_map = np.zeros((img_height, img_width), dtype=int)
idx_counter = 0 # To iterate through all_labels_full_eval and all_preds_full_eval

for r in range(img_height):
    for c in range(img_width):
        if gt_data[r, c] != 0: # Process only non-background pixels
            true_label = all_labels_full_eval[idx_counter]
            predicted_label = all_preds_full_eval[idx_counter]
            is_correct = (true_label == predicted_label)
            is_edge = is_edge_pixel_map[r, c]

            if is_edge:
                if is_correct:
                    vis_map[r, c] = 1 # Correct edge
                else:
                    vis_map[r, c] = 2 # Misclassified edge
            else: # Not an edge pixel
                if is_correct:
                    vis_map[r, c] = 3 # Correct non-edge
                else:
                    vis_map[r, c] = 4 # Misclassified non-edge
            idx_counter += 1

# Define a custom colormap for the visualization map
colors_vis = [
    'beige',      # 0: Background
    'lightgreen', # 1: Correctly classified edge pixel
    'red',        # 2: Misclassified edge pixel
    'lightblue',  # 3: Correctly classified non-edge pixel (different from edge for contrast)
    'purple'      # 4: Misclassified non-edge pixel
]
cmap_vis = mcolors.ListedColormap(colors_vis)
bounds_vis = np.arange(len(colors_vis) + 1) - 0.5
norm_vis = mcolors.BoundaryNorm(bounds_vis, cmap_vis.N)

plt.figure(figsize=(15, 10))

plt.subplot(1, 2, 1)
plt.imshow(gt_data, cmap=cmap_sampled, norm=norm_sampled) # Reuse previous GT map
plt.title('Ground Truth Image')
plt.colorbar(label='Class Label', ticks=np.arange(num_classes) + 0.5, format=plt.FuncFormatter(lambda x, p: int(x)))
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(vis_map, cmap=cmap_vis, norm=norm_vis)
plt.title('Edge/Boundary Pixel Analysis (Sampled Model)')
cbar = plt.colorbar(cmap=cmap_vis, norm=norm_vis, boundaries=bounds_vis, ticks=[0, 1, 2, 3, 4])
cbar.set_ticklabels(['Background', 'Correct Edge', 'Misclassified Edge', 'Correct Non-Edge', 'Misclassified Non-Edge'])
plt.axis('off')

plt.tight_layout()
plt.show()