# -*- coding: utf-8 -*-
"""Loader and training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""

from torch.utils.data import Dataset, DataLoader

# 1. Define a custom PyTorch Dataset class named HSIDataset
class HSIDataset(Dataset):
    def __init__(self, data, labels):
        # 2. In the __init__ method of HSIDataset, accept data and labels as arguments and store them as attributes.
        self.data = data
        self.labels = labels

    def __len__(self):
        # 3. Implement the __len__ method to return the total number of samples in the dataset.
        return len(self.labels)

    def __getitem__(self, idx):
        # 4. Implement the __getitem__ method to return the data and label for a given index.
        return self.data[idx], self.labels[idx]

# 5. Create instances of HSIDataset for the training set and the testing set.
train_dataset = HSIDataset(X_train, y_train)
test_dataset = HSIDataset(X_test, y_test)

# Define batch size
batch_size = 64

# 6. Create a DataLoader for the train_dataset
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# 7. Create a DataLoader for the test_dataset
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# 8. Print the number of batches in both the training and testing DataLoaders
print(f"Number of batches in training DataLoader: {len(train_dataloader)}")
print(f"Number of batches in testing DataLoader: {len(test_dataloader)}")



import torch
import torch.nn as nn
import torch.optim as optim
from tqdm.notebook import tqdm # For progress bar
import time # Import the time module

# 1. Determine in_channels from X_train
in_channels = X_train.shape[1]

# 2. Determine num_classes from y_train
# The labels are 0-indexed, so the number of classes is max_label + 1
num_classes = int(y_train.max().item()) + 1

print(f"Input channels: {in_channels}")
print(f"Number of classes: {num_classes}")

# 3. Instantiate the MFA_CLA_3DCNN_HSI_Classifier model
model = MFA_CLA_3DCNN_HSI_Classifier(
    in_channels=in_channels,
    num_classes=num_classes,
    stem_channels=32,
    embed_dim=128,
    patch_size=patch_size, # Use the patch_size defined in previous steps
    depth=2,
    num_heads=4,
    latent_dim=64
)

# 4. Define a loss function
criterion = nn.CrossEntropyLoss()

# 5. Define an optimizer
learning_rate = 1e-3
optimizer = optim.AdamW(model.parameters(), lr=learning_rate)

# 6. Check for GPU availability and set the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print(f"Model moved to device: {device}")

# Training parameters
num_epochs = 10 # Can be adjusted based on performance

best_accuracy = 0.0
total_train_time = 0
total_val_time = 0

# 7. Implement a training loop
for epoch in range(num_epochs):
    epoch_start_time = time.time()

    model.train() # Set model to training mode
    running_loss = 0.0

    # Wrap train_dataloader with tqdm for a progress bar
    for batch_idx, (data, labels) in enumerate(tqdm(train_dataloader, desc=f"Epoch {epoch+1} Training")):
        data, labels = data.to(device), labels.to(device)

        optimizer.zero_grad() # Zero out gradients
        outputs = model(data) # Forward pass
        loss = criterion(outputs, labels) # Calculate loss
        loss.backward() # Backward pass
        optimizer.step() # Update weights

        running_loss += loss.item() * data.size(0)

    epoch_train_time = time.time() - epoch_start_time
    total_train_time += epoch_train_time

    epoch_loss = running_loss / len(train_dataloader.dataset)
    print(f"\nEpoch [{epoch+1}/{num_epochs}], Training Loss: {epoch_loss:.4f}")

    # 8. Validation step
    val_start_time = time.time()
    model.eval() # Set model to evaluation mode
    val_running_loss = 0.0
    correct_predictions = 0
    total_samples = 0

    with torch.no_grad(): # Disable gradient calculations
        # Wrap test_dataloader with tqdm for a progress bar
        for data, labels in tqdm(test_dataloader, desc=f"Epoch {epoch+1} Validation"):
            data, labels = data.to(device), labels.to(device)
            outputs = model(data)
            loss = criterion(outputs, labels)

            val_running_loss += loss.item() * data.size(0)

            _, predicted = torch.max(outputs.data, 1)
            total_samples += labels.size(0)
            correct_predictions += (predicted == labels).sum().item()

    epoch_val_time = time.time() - val_start_time
    total_val_time += epoch_val_time

    val_loss = val_running_loss / len(test_dataloader.dataset)
    accuracy = 100 * correct_predictions / total_samples
    print(f"Validation Loss: {val_loss:.4f}, Accuracy: {accuracy:.2f}%")

    # 9. Keep track of the best model
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        torch.save(model.state_dict(), 'best_mfa_cla_hsi_classifier.pth')
        print(f"Saved Best Model with Accuracy: {best_accuracy:.2f}%")

print("\nTraining complete.")

# Calculate and print average times
print(f"Average Training Time per Epoch: {total_train_time / num_epochs:.2f} seconds")
print(f"Average Validation Time per Epoch: {total_val_time / num_epochs:.2f} seconds")