# -*- coding: utf-8 -*-
"""MFA_CLA_EncoderBlock .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""



class MFA_CLA_EncoderBlock(nn.Module):
    def __init__(self, embed_dim, num_heads, latent_dim, mlp_ratio=4.0):
        super().__init__()

        self.norm1 = nn.LayerNorm(embed_dim)
        self.attn = MFA_CLA_Attention(embed_dim, num_heads, latent_dim)

        self.norm2 = nn.LayerNorm(embed_dim)
        hidden = int(embed_dim * mlp_ratio)

        self.mlp = nn.Sequential(
            nn.Linear(embed_dim, hidden),
            nn.GELU(),
            nn.Linear(hidden, embed_dim)
        )

    def forward(self, x, shared_k=None, shared_v=None):
        attn_out, k, v = self.attn(self.norm1(x), shared_k, shared_v)
        x = x + attn_out
        x = x + self.mlp(self.norm2(x))
        return x, k, v