# -*- coding: utf-8 -*-
"""MFA_CLA_Attention .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""

class MFA_CLA_Attention(nn.Module):
    """
    MFA with Cross-Layer Shared KV
    """
    def __init__(self, embed_dim, num_heads, latent_dim):
        super().__init__()
        self.num_heads = num_heads
        self.latent_dim = latent_dim

        self.Sq = nn.Linear(embed_dim, latent_dim, bias=False)
        self.Sk = nn.Linear(embed_dim, latent_dim, bias=False)
        self.Sv = nn.Linear(embed_dim, latent_dim, bias=False)

        self.Qc = nn.Parameter(torch.randn(num_heads, latent_dim, latent_dim) * 0.02)
        self.Oc = nn.Parameter(torch.randn(num_heads, latent_dim, embed_dim) * 0.02)

        self.scale = latent_dim ** -0.5

    def forward(self, x, shared_k=None, shared_v=None):
        q = self.Sq(x)

        if shared_k is None or shared_v is None:
            k = self.Sk(x)
            v = self.Sv(x)
        else:
            k, v = shared_k, shared_v

        out = 0.0
        for h in range(self.num_heads):
            qh = q @ self.Qc[h]
            attn = (qh @ k.transpose(-2, -1)) * self.scale
            attn = attn.softmax(dim=-1)
            out = out + (attn @ v) @ self.Oc[h]

        return out, k, v