# -*- coding: utf-8 -*-
"""MFA_CLA_TransformerEncoder .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""

class MFA_CLA_TransformerEncoder(nn.Module):
    """
    Cross-Layer KV shared Transformer Encoder
    """
    def __init__(self, depth, embed_dim, num_heads, latent_dim):
        super().__init__()
        self.layers = nn.ModuleList([
            MFA_CLA_EncoderBlock(embed_dim, num_heads, latent_dim)
            for _ in range(depth)
        ])

    def forward(self, x):
        shared_k, shared_v = None, None
        for i, layer in enumerate(self.layers):
            if i == 0:
                x, shared_k, shared_v = layer(x)
            else:
                x, _, _ = layer(x, shared_k, shared_v)
        return x