# -*- coding: utf-8 -*-
"""MFA_CLA_3DCNN_HSI_Classifier .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""

class MFA_CLA_3DCNN_HSI_Classifier(nn.Module):
    def __init__(
        self,
        in_channels,
        num_classes,
        stem_channels=32,
        embed_dim=128,
        patch_size=4,
        depth=4,
        num_heads=4,
        latent_dim=64
    ):
        super().__init__()

        self.stem = SpectralSpatial3DCNNStem(stem_channels)

        self.patch_embed = HSIPatchEmbedding(
            stem_channels, embed_dim, patch_size
        )

        self.encoder = MFA_CLA_TransformerEncoder(
            depth, embed_dim, num_heads, latent_dim
        )

        self.norm = nn.LayerNorm(embed_dim)
        self.head = nn.Linear(embed_dim, num_classes)

    def forward(self, x):
        x = self.stem(x)        # (B, C, H, W)
        x = self.patch_embed(x)# (B, N, D)
        x = self.encoder(x)    # (B, N, D)
        x = self.norm(x)
        x = x.mean(dim=1)
        return self.head(x)