# -*- coding: utf-8 -*-
"""Patch_Embedding .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""

class HSIPatchEmbedding(nn.Module):
    """
    Convert feature maps to tokens
    """
    def __init__(self, in_channels, embed_dim, patch_size):
        super().__init__()
        self.proj = nn.Conv2d(
            in_channels, embed_dim,
            kernel_size=patch_size,
            stride=patch_size
        )

    def forward(self, x):
        x = self.proj(x)                 # (B, D, H/P, W/P)
        x = x.flatten(2).transpose(1,2) # (B, N, D)
        return x