# -*- coding: utf-8 -*-
"""Quantitative measures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""

from sklearn.metrics import confusion_matrix, cohen_kappa_score
import torch
import numpy as np

# Ensure the model is in evaluation mode and on the correct device
model.eval()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Load the best model weights
try:
    model.load_state_dict(torch.load('best_mfa_cla_hsi_classifier.pth'))
    print("Successfully loaded best model weights.")
except FileNotFoundError:
    print("Error: Best model weights file 'best_mfa_cla_hsi_classifier.pth' not found.")
    print("Please ensure the training cell was run and the model was saved.")
    exit()

all_preds = []
all_labels = []

with torch.no_grad():
    for data, labels in test_dataloader:
        data, labels = data.to(device), labels.to(device)
        outputs = model(data)
        _, predicted = torch.max(outputs.data, 1)
        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

# 1. Calculate Overall Accuracy (OA)
oa = np.sum(all_preds == all_labels) / len(all_labels)
print(f"\nOverall Accuracy (OA): {oa:.4f}")

# 2. Calculate Kappa Coefficient
kappa = cohen_kappa_score(all_labels, all_preds)
print(f"Kappa Coefficient: {kappa:.4f}")

# 3. Calculate Average Accuracy (AA)
cm = confusion_matrix(all_labels, all_preds)

# Per-class accuracy
per_class_accuracy = []
for i in range(num_classes):
    correct_predictions_class_i = cm[i, i]
    total_samples_class_i = np.sum(cm[i, :])
    if total_samples_class_i > 0:
        per_class_accuracy.append(correct_predictions_class_i / total_samples_class_i)
    else:
        per_class_accuracy.append(0.0) # If a class has no samples in test set

# Average Accuracy
aa = np.mean(per_class_accuracy)
print(f"Average Accuracy (AA): {aa:.4f}")

print("\nPer-class Accuracies:")
for i, acc in enumerate(per_class_accuracy):
    print(f"  Class {i}: {acc:.4f}")