# -*- coding: utf-8 -*-
"""train_test_split.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUkKqA1I0pI_7LMvyE0He-q1zrH90bF
"""

import numpy as np
import torch

# 1. Access the raw hyperspectral image data and ground truth
hsi_data = pavia_u_data['paviaU']
gt_data = pavia_u_gt['paviaU_gt']

print(f"Original HSI data shape: {hsi_data.shape}")
print(f"Original Ground Truth data shape: {gt_data.shape}")

# 2. Normalize the hyperspectral image data by dividing it by its maximum value
normalized_hsi_data = hsi_data / hsi_data.max()

# 3. Define a patch_size
patch_size = 11

# 4. Calculate the amount of padding needed
padding_amount = patch_size // 2

# 5. Apply symmetric padding to normalized_hsi_data
padded_hsi_data = np.pad(
    normalized_hsi_data,
    ((padding_amount, padding_amount), (padding_amount, padding_amount), (0, 0)),
    mode='constant', constant_values=0
)

print(f"Padded HSI data shape: {padded_hsi_data.shape}")

# Get dimensions
img_height, img_width, num_bands = hsi_data.shape

# 6. Initialize two empty Python lists
all_patches = []
all_labels = []

# 7. Iterate through each pixel's spatial coordinates
for r in range(img_height):
    for c in range(img_width):
        # Check if the ground truth label is not equal to 0 (background)
        if gt_data[r, c] != 0:
            # Extract a (patch_size, patch_size, num_bands) block
            patch = padded_hsi_data[
                r:r + patch_size,
                c:c + patch_size,
                :
            ]
            # Transpose to (num_bands, patch_size, patch_size)
            patch = np.transpose(patch, (2, 0, 1))

            all_patches.append(patch)
            # Append 0-indexed class label
            all_labels.append(gt_data[r, c] - 1)

# 8. Convert all_patches list into a PyTorch tensor of type torch.float32
all_patches_tensor = torch.tensor(np.array(all_patches), dtype=torch.float32)

# 9. Convert all_labels list into a PyTorch tensor of type torch.long
all_labels_tensor = torch.tensor(np.array(all_labels), dtype=torch.long)

# 10. Print the shapes of the final tensors
print(f"Shape of all_patches_tensor: {all_patches_tensor.shape}")
print(f"Shape of all_labels_tensor: {all_labels_tensor.shape}")



from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    all_patches_tensor, all_labels_tensor, test_size=0.95, random_state=42
)

# Print the shapes of the resulting tensors
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")